WARRIOR - 战士,INQUISITOR - 审判官,GUARDIAN - 守护者,TEMPLAR - 圣殿骑士
ARCHER - 弓箭手,SCOUT - 童子军,SHARPSHOOTER - 精准射手,TRAPPER - 陷阱师
MAGE - 法师,ELEMENTALIST - 元素师,SUMMONER - 召唤师,WARLOCK - 术士
DEMONOLOGIST - 恶魔学家,NECROMANCER - 死灵法师,BEASTMASTER - 兽王, 
MONK - 僧侣,KENSEI - 剑圣,SHUGOKI - 守护鬼,SHINOBI - 忍者
ROGUE - 盗贼,ASSASSIN - 刺客,IRON MAIDEN - 铁处女,BOMBARDIER - 爆破手
SAVAGE - 野蛮人,BERSERKER - 狂战士,EXECUTIONER - 行刑者,GLADIATOR - 角斗士
THRAEX - 短剑角斗士,MURMILLO - 重装角斗士,DIMACHAERUS - 双刀角斗士,SECUTOR - 追击角斗士