战士,第1职业特殊潜能
currentstrengthincreasedbyipoints,当前力量：增加xx点
currentmagicincreasedbyipoints,当前魔法：增加xx点
currentdexterityincreasedbyipoints,当前敏捷：增加xx点
currentvitalityincreasedbyipoints,当前体力：增加xx点
Lifeincreasedbyi,生命增加xx点
Liferegenerationincreasedbyi,生命回复：增加xx点
Manaincreasedbyi,法力增加xx点
Manaregenerationincreasedbyi,法力回复：增加xx点
Meleedamageresistanceincreasedbyi,近战伤害抵抗：增加xx点
Arrowdamageresistanceincreasedbyi,箭矢伤害抵抗：增加xx点
idamagefromenemies,敌人对你造成xx点伤害
ichancetoresistknockbackeffect,+xx% 击退效果抵抗几率
itostunthreshold,+xx 晕眩阈值
itoarmorclass,+xx 护甲等级
itoallresistance,+xx 全抗性
itoblockchance,+xx% 格挡几率
iliferegenerationatthetimeofblockingandhitrecovery,阻挡时生命回复增加xx点，并增加击中恢复速度
minimalchancetogethitinmeleecombatbymonstersgetsreducedbyi,近战怪物对你的命中几率降低xx%
itoaccuracy,+xx 命中准确率
ipointstodamageinmeleecombat,近战伤害增加xx点
meleeattackdamageincreasedbyipointswhileholdingashield,持盾时近战攻击伤害增加xx点
ipointstodamagewithrangedweapons,远程武器伤害增加xx点
icriticaldamage,+xx% 致命伤害
Hitsrequireilessdamagetostunmonsters,攻击需要的伤害值减少xx%以晕眩怪物
ichanceofcriticalhits,+xx% 暴击几率
idamagetoundeadinmeleecombat,近战对不死生物的伤害增加xx%
canseetrappedobjects,可以看到陷阱物品
idamagefromtraps,受陷阱伤害减少xx%
itoexperiencepointsgained,获得经验点数增加xx%
amountofgoldfoundincreasedbyipieces,发现金币数量增加xx个
ichancetofindmagicrareanduniqueitems,获得魔法、稀有和唯一物品的几率增加xx%
Givesichancetogetarandomelixirfromuniquemonsters,击败唯一怪物后有xx%几率获得随机圣水
gainistatpointsperleveluptodistribute,每次升级获得额外的xx属性点进行分配
immediatelygainanextralevel,立即获得额外一级！
idiscountwhenpurchasingfromtraders,从商贩处购买时享受xx%的折扣
ichanceforitemstoavoidlosingdurability,物品避免损坏的几率增加xx%
decreaseschanceforaweapontolosedurabilitybyipoints,减少武器损坏的几率xx点
itemequiprequirementsarereducedbyipoints,装备要求降低xx点
monsterscannotstealmanafromyou,怪物无法从你身上偷取法力
manastealeffectivenessaswellasmaximummanastolenperhitcapgetincreasedbyi,法力偷取效果以及每次攻击最多偷取的法力值上限增加xx%
lifestealeffectivenessaswellasmaximumlifestolenperhitcapgetincreasedbyi,生命偷取效果以及每次攻击最多偷取的生命值上限增加xx%
furydurationincreasedbyiseconds,狂怒持续时间增加xx秒
healingspellorrelictwillrestoreimorehealth,治疗法术（或神器）将恢复额外的xx%生命值
basicregenerationoflifeandmanaoutsideofbattleincreasedbyi,战斗外的生命和法力基础回复速度增加xx%
lifeincreasedbyi,生命增加xx点
manaincreasedbyi,法力增加xx点
yourskillattradinggetsyoumorediscountsextraidecreaseinpriceswhenpurchasingfromtraders,你在交易方面的技能使你能够享受更多折扣！从商贩处购买时价格额外降低xx%
regenerationoflifeandmanagetsincreasedbyi,生命和法力的回复速度增加xx
amountofgoldfoundincreasedbyipieces,发现的金币数量增加xx个
icriticaldamageitoaccuracy,+xx% 致命伤害，+xx 命中准确率
hittingmonstersinmeleeadditionalystealsipointsoflifeandipointsofmana,在近战中攻击怪物时，额外偷取xx点生命和xx点法力
accuracyimeleeattackdamageiarmorclassi,命中准确率：+xx，近战攻击伤害：+xx，护甲等级：+xx
affixesthatincreaseVitalityandMagicadditolifemana,增加Vitality和Magic属性的词缀将使生命和法力增加xx%
allattributesipoints,所有属性值增加xx点
ilayersofreflect,+xx层反射效果
resistallimaximumresistancei,全抗性：+xx，最大抗性：+xx%
Furycooldowngetsdecreasedbyiseconds,狂怒技能冷却时间减少xx秒
reflectcooldownreducedbyiseconds,反射技能冷却时间减少xx秒
damagefromphysicalspellsgetsreducedbyi,来自物理法术的伤害减少xx%
Meleedamageresistanceincreasedbyi,近战伤害抵抗增加xx
itoarmorclass,护甲等级增加+xx
itoallresistance,所有抗性增加+xx
idamagefromenemies,来自敌人的xx伤害
idamagefromtrapsamountofgoldfoundgetsincreasedbyi,陷阱伤害减少xx%，发现的金币数量增加xx个
itomaximumlevelofitemssoldinshops,商店中出售物品的最高等级增加+xx
chancesofgettinghitinmeleecombatgetdecreasedbyi,近战战斗中被击中的几率降低xx%
chancesofgettinghitinrangedcombatgetdecreasedbyi,远程战斗中被击中的几率降低xx%
maximummeleeandarrowdamageresistanceincreasedbyiminimumchancetobehitwithmeleehitsandarrowsgetsincreasedbyi,近战和箭矢伤害抵抗上限增加xx%，近战和箭矢被命中的最低几率增加xx%
gainimorestatpointperleveluptodistribute,每次升级获得额外的xx属性点进行分配
allbaseattributelimitsraisedbyipoints,所有基础属性的限制增加xx点
战士,第2职业特殊潜能
fieryelementaldamagefromweaponsisincreasedadditionallybyi,武器的火焰元素伤害额外增加xx%
lightningelementaldamagefromweaponsisincreasedadditionallybyi,武器的闪电元素伤害额外增加xx%
coldelementaldamagefromweaponsisincreasedadditionallybyi,武器的冰冷元素伤害额外增加xx%
arcaneelementaldamagefromweaponsisincreasedadditionallybyi,武器的奥术元素伤害额外增加xx%
战士,第3职业独特潜能
basiclifemanaregenerationisnotreducedwhileperformingattacksandcasting,在进行攻击和施放技能时，基础生命和法力回复速度不会降低
letsyourmeleeweaponsignoreuniquemonstersdfeandincreaseyourdamageagainstthembyi,使你的近战武器可以无视唯一怪物的防御，并增加对它们的伤害xx%
ichancetoreducedamagereceivedbyi,xx% 几率减少受到的伤害xx%
weapondamageiaccuracyi,武器伤害增加xx%，命中准确率增加xx
manaincreasedbyimanaregenerationincreasedbyi,法力增加xx，法力回复速度增加xx
LifeincreasedbyiLiferegenerationincreasedbyi,生命增加xx，生命回复速度增加xx
战士,第4职业独特潜能
damageinrangedcombatincreasedbyipointsimanaregeneration,远程战斗中的伤害增加xx点，法力回复速度减少xx
whenatfulllifedealidamageinmeleecombat,在满血状态下，近战战斗中造成+xx%的伤害
accuracyforspellsfrommonstersagainstyougetsdecreasedbyi,怪物对你施放的法术的命中准确率降低xx%
accuracyirangedattackdamagei,命中准确率：+xx，远程攻击伤害：+xx
maximumandcurrentblockchanceimeleebasedamagei,最大和当前的格挡几率降低xx%，近战基础伤害增加xx%
meleeandrangedautohitimprovedbyi,近战和远程自动命中几率提高xx%
弓箭手,第1职业独特潜能
totaldamagetobeastswitharrowsboltstrapsincreasedbyi,对野兽使用箭矢/弩矢/陷阱的总伤害增加xx%
totaldamagetoundeadwitharrowsboltstrapsincreasedbyi,对不死生物使用箭矢/弩矢/陷阱的总伤害增加xx%
totaldamagetodemonswitharrowsboltstrapsincreasedbyi,对恶魔使用箭矢/弩矢/陷阱的总伤害增加xx%
damageforsidearrowsincreasedbyi,侧翼箭矢的伤害增加xx%
WallsandRingsofFireandLightninglastisecondslonger,火墙和闪电之环的持续时间延长xx秒
damageincreasedbyi,伤害增加xx
弓箭手,第2职业独特潜能
ichancetoavoidgettingstunned,xx% 几率避免被眩晕
holyelementaldamagefromweaponsisincreasedadditionallybyi,武器的神圣元素伤害额外增加xx%
acidelementaldamagefromweaponsisincreasedadditionallybyi,武器的酸性元素伤害额外增加xx%
acidelementaldamagefromweaponsisincreasedadditionallybyi,武器的酸性元素伤害额外增加xx%
弓箭手,第3职业独特潜能
distancetotargetreducesaccuracyonlybyhalf,与目标的距离只会使准确率降低一半
magicalandarrowtrapshaveichancetohityou,魔法和箭矢陷阱对你命中的几率降低xx%
弓箭手,第4职业独特潜能
useboltheadsthatpierceioftargetsdfe,使用能穿透目标防御力（DFE）xx%的弩头
golemmagicresistancesareincreasedbyi,傀儡的魔法抗性增加xx%
魔法师,第1职业独特潜能
ichancetohitwithspellsandflasks,+xx% 施法和药剂命中几率
Passivelygainexperiencepointsspeedfactori,被动获得经验点速度因子：xx
Hydraamountlimitincreasedbyi,水蛇数量上限增加xx
excessivemanashielddamagereducedadditionallybyi,过度的法力护盾伤害额外减少xx%
levelsforallspellsareincreasedbyi,所有法术的等级增加xx级
firespelldamagegetsincreasedbyi,火焰法术伤害增加xx%
lightningspelldamagegetsincreasedbyi,闪电法术伤害增加xx%
arcanespelldamagegetsincreasedbyi,奥术法术伤害增加xx%
GivesoneextraGolem,额外获得一个魔像
damageofallspelltypesgetsincreasedbyi,所有法术类型的伤害增加xx%
cooldownfornovaspellsreducedbyiseconds,新星法术的冷却时间减少xx秒
excessivemanashielddamagegetsreducedadditionallybyi,过度的法力护盾伤害额外减少xx%
魔法师,第2职业独特潜能
CastimoreLightningchains,施放xx条更多的闪电链
coldspelldamagegetsincreasedbyi,冰冷法术伤害增加xx%
魔法师,第3职业独特潜能
ipointstodamageofsummonedminions,召唤的随从的伤害增加xx点
itohitpointsofsummonedminions,召唤的随从的生命值增加xx
ipointstoarmorofsummonedminions,召唤的随从的护甲增加xx点
ipointstoaccuracyofsummonedminions,召唤的随从的命中准确率增加xx点
damageofallminionsgetsincreasedbyipoints,所有随从的伤害增加xx点
魔法师,第4职业独特潜能
bonespiritdamagedividergetsdecreasedbyi,骨之灵伤害分配系数减少xx
acidspelldamagegetsincreasedbyi,酸性法术伤害增加xx%
physicalspelldamagegetsincreasedbyi,物理法术伤害增加xx%
castingdoesntreducemanaregenerationspeed,施放法术不会降低法力回复速度
acidburningspeedgetsincreasedbyi,酸性灼烧速度增加xx%
和尚,第1职业独特潜能
idamagetodemonsinmeleecombat,对恶魔的近战伤害增加xx%
damagetoadjacentmeleetargetsincreasedbyi,对相邻的近战目标的伤害增加xx%
lateralattackaccuracygetsincreasedbyi,横向攻击的命中准确率增加xx%
和尚,第2职业独特潜能
ichancetobypassmeleedamageresistanceandDFEofthetarget,xx% 的几率绕过目标的近战伤害抗性（和防御力）
Minimumandmaximumchancestogethitwithspellsarereducedbyi,使用法术受到攻击的最小和最大几率降低xx%
regenerateioflifepersecond,每秒回复生命值的 +xx%
和尚,第3职业独特潜能
chanceforcriticalhitfurtherincreasedbyicriticalhitdamagefurtherincreasedbyi,暴击几率进一步增加xx%，暴击伤害进一步增加xx%
和尚,第4职业独特潜能
dealidamagetomonsterinmeleecombatifithaslessthan20percenthitpoints,如果怪物的生命值低于20%，在近战战斗中造成+xx%的伤害
etherealizedurationincreasedbyiseconds,虚幻化持续时间增加xx秒
icritchanceicriticaldamagemeleedamageresistanceincreasedbyiarrowdamageresistanceincreasedbyi,+xx% 暴击几率，+xx% 暴击伤害，近战伤害抗性增加xx，箭矢伤害抗性增加xx
minimalhitpointsneededformonsterstogetimproveddamageincreasedtoi,怪物需要的最低生命值才能受到改善伤害的要求增加至xx%
刺客,第1职业独特潜能
idamagetobeastsinmeleecombat,近战战斗中对野兽的伤害增加xx%
minimumandmaximumchancestogethitwithmeleeweaponsandarrowsreducedadditionallybyi,使用近战武器和箭矢受到攻击的最小和最大几率额外降低xx%
monsterchainactivationradiusdecreasedbyi,怪物连锁激活半径减少xx
ifcurrenthitpointsarereducedbelow40percentcriticalhitchancewillbeincreasedbyi,如果当前生命值降低到40%以下，暴击几率将增加xx%
刺客,第2职业独特潜能
clawattacksagainstmonsterswithlessthanihitpointskilltheminstantlydoesntworkvsbosses,对生命值低于xx%的怪物进行爪击将立即杀死它们（对Boss无效）。
刺客,第3职业独特潜能
Thornsdamageforeacharmorpiecewornthathasthornsonitgetsincreasedbyi,每件穿戴的带有荆棘属性的护甲，荆棘伤害增加xx
ipointstolifeeachtimeyougethit,每次被击中时，生命值增加+xx点
reflectarrowsbackelementalarrowsnotaffectedatattackingmonstersreboundchanceirebounddamageiarmorreducedbyi,将箭矢反弹回攻击的怪物（不包括元素箭矢），反弹几率：xx%，反弹伤害增加：xx%，护甲降低xx
刺客,第4职业独特潜能
fireflaskdamagegetsincreasedbyi,火焰烧瓶伤害增加xx%
arcaneflaskdamagegetsincreasedbyi,奥术烧瓶伤害增加xx%
lightningflaskdamagegetsincreasedbyi,闪电烧瓶伤害增加xx%
acidflaskdamagegetsincreasedbyi,酸性烧瓶伤害增加xx%
野蛮人,第1职业独特潜能
meleeattacksagainstmonsterswithmorethan90percenthitpointsdealimoredamage,对生命值高于90%的怪物进行近战攻击时，伤害增加xx%
maximalhitpointsneededformonsterstogetincreaseddamagereducedfurtherbyi,怪物需要获得增加伤害的最大生命值进一步减少xx%
野蛮人	第2职业独特潜能
basicregenerationoflifeimprovedbyiinbattle	战斗中基础生命回复速度提高xx%
furyincreasesaccuracyadditionallybyi	狂怒状态额外增加命中准确率xx
furyincreasesdamagefromweaponsbyi	狂怒状态使武器伤害额外增加xx
furyincreasesarmorbyadditionalipoints	狂怒状态额外增加护甲值xx点
furyreducesdamagefromenemiesbyipoints	狂怒状态减少来自敌人的伤害xx点
furyincreasesstunthresholdbyipoints	狂怒状态增加晕眩阈值xx点
furycooldownshortenedbyiseconds	狂怒状态冷却时间缩短xx秒
野蛮人,第3职业独特潜能
attackingdoesntreduceliferegenerationspeed,攻击不会降低生命回复速度。
野蛮人,第4职业(1分支)独特潜能
whenlowonhitpointsbelow40percentliferegenerationgetsincreasedbyi,当生命值低于40%时，生命回复速度增加xx。
野蛮人,第4职业(2分支)独特潜能
whenwieldingswordormacewithshieldattackspeedisimprovedbyiframe,当持有剑（或锤）和盾牌时，攻击速度提高xx帧。
野蛮人,第4职业(3分支)独特潜能
Arrowdamageresistanceicurrentresistanceiresistancecaps,箭矢伤害抗性：当前抗性增加+xx，抗性上限增加+xx%。
ichancetoblockmeleehitsfromenemiesifwieldingtwoidenticalweapontypes,当持有两个相同的武器类型时，有xx%的几率格挡来自敌人的近战攻击。
knockbackresistancechancegetsincreasedbyi,击退抗性几率增加xx%。
野蛮人,第4职业(4分支)独特潜能
striketargetharderwhenyouseeopportunityichanceofinflictingextraimeleedamage,当你看到机会时，打击目标更强，有xx%几率造成额外xx%的近战伤害。
furydecreasestimeofstunrecoverybyiframes,狂怒状态减少晕眩恢复时间xx帧。
stunrecoveryspeedisimprovedbyiframe,晕眩恢复速度提高xx帧。
使用特质后出现的潜能,特质潜能
baseattributesumlimitraisedbyipoints,基础属性总和限制增加xx点。
ichancetoreducetotalincomingdamageby80percent,xx% 几率将总体受到的伤害减少80%
idamagewithbows,使用弓增加+xx伤害
usearrowheadsthatpierceioftargetsdfe,使用可以穿透目标防御力（DFE）xx%的箭头
itoaccuracyipointstodamageitoarmorclass,增加+xx命中准确率，+xx点伤害，+xx护甲等级
getimoreperkpointslifemanaregenerationdecreasedbyiallstatsdecreasedbyi,获得额外的xx个特技点，生命和法力回复速度减少xx，所有属性减少xx
icriticalhitdamage,增加+xx%的暴击伤害